//
//  UIRecipeView.swift
//  Bron
//
//  Renders UI Recipes generated by Claude
//  Placeholder for PR-04 implementation
//

import SwiftUI

struct UIRecipeView: View {
    let recipe: UIRecipe
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Header
            if let title = recipe.title {
                Text(title)
                    .font(.headline)
            }
            
            if let description = recipe.description {
                Text(description)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }
            
            // Component rendering based on type
            // To be implemented in PR-04
            switch recipe.componentType {
            case .form:
                Text("Form component - Coming in PR-04")
                    .foregroundStyle(.secondary)
            case .picker:
                Text("Picker component - Coming in PR-04")
                    .foregroundStyle(.secondary)
            case .confirmation:
                Text("Confirmation component - Coming in PR-04")
                    .foregroundStyle(.secondary)
            case .fileUpload:
                Text("File upload component - Coming in PR-04")
                    .foregroundStyle(.secondary)
            }
        }
        .padding()
        .background(Color(.systemGray6))
        .clipShape(RoundedRectangle(cornerRadius: 12))
    }
}

#Preview {
    UIRecipeView(recipe: .preview)
        .padding()
}

