//
//  UIRecipe.swift
//  Bron
//
//  UI Recipe model for dynamic UI generation
//

import Foundation

/// Represents a UI Recipe generated by Claude for structured input
struct UIRecipe: Identifiable, Codable, Hashable {
    let id: UUID
    let componentType: UIComponentType
    let schema: [String: SchemaField]
    let requiredFields: [String]
    var title: String?
    var description: String?
    
    init(
        id: UUID = UUID(),
        componentType: UIComponentType,
        schema: [String: SchemaField] = [:],
        requiredFields: [String] = [],
        title: String? = nil,
        description: String? = nil
    ) {
        self.id = id
        self.componentType = componentType
        self.schema = schema
        self.requiredFields = requiredFields
        self.title = title
        self.description = description
    }
}

/// UI component types
enum UIComponentType: String, Codable {
    case form
    case picker
    case confirmation
    case fileUpload
}

/// Schema field definition
struct SchemaField: Codable, Hashable {
    let type: FieldType
    var label: String?
    var placeholder: String?
    var options: [String]?
    var validation: FieldValidation?
}

/// Field types
enum FieldType: String, Codable {
    case text
    case number
    case date
    case email
    case phone
    case select
    case multiSelect
    case file
    case boolean
}

/// Field validation rules
struct FieldValidation: Codable, Hashable {
    var required: Bool?
    var minLength: Int?
    var maxLength: Int?
    var pattern: String?
}

// MARK: - Preview Helpers

extension UIRecipe {
    static var preview: UIRecipe {
        UIRecipe(
            componentType: .form,
            schema: [
                "amount": SchemaField(type: .number, label: "Amount", placeholder: "0.00"),
                "date": SchemaField(type: .date, label: "Receipt Date"),
                "category": SchemaField(type: .select, label: "Category", options: ["Food", "Transport", "Office"])
            ],
            requiredFields: ["amount", "date"],
            title: "Receipt Details",
            description: "Please provide the receipt information"
        )
    }
}

