//
//  UIRecipe.swift
//  Bron
//
//  UI Recipe model for dynamic UI generation
//

import Foundation

/// Represents a UI Recipe generated by Claude for structured input
struct UIRecipe: Identifiable, Codable, Hashable {
    let id: UUID
    let componentType: UIComponentType
    let schema: [String: SchemaField]
    let requiredFields: [String]
    var title: String?
    var description: String?
    var style: UIStyle?
    
    // Submission state
    var isSubmitted: Bool
    var submittedData: [String: String]?
    
    init(
        id: UUID = UUID(),
        componentType: UIComponentType,
        schema: [String: SchemaField] = [:],
        requiredFields: [String] = [],
        title: String? = nil,
        description: String? = nil,
        style: UIStyle? = nil,
        isSubmitted: Bool = false,
        submittedData: [String: String]? = nil
    ) {
        self.id = id
        self.componentType = componentType
        self.schema = schema
        self.requiredFields = requiredFields
        self.title = title
        self.description = description
        self.style = style
        self.isSubmitted = isSubmitted
        self.submittedData = submittedData
    }
}

// MARK: - Styling

/// Pre-defined style presets for common branding
enum UIStylePreset: String, Codable, CaseIterable {
    // Platform defaults
    case `default`
    case minimal
    
    // Brand presets
    case google
    case apple
    case microsoft
    case github
    case slack
    case notion
    case spotify
    
    // Category-based
    case professional
    case casual
    case urgent
    case success
    case warning
    case error
    
    // Content-specific
    case email
    case calendar
    case weather
    case financial
    case health
}

/// Styling configuration for UI Recipes
struct UIStyle: Codable, Hashable {
    // Preset (optional - overrides custom values)
    var preset: UIStylePreset?
    
    // Colors (hex strings)
    var primaryColor: String?
    var secondaryColor: String?
    var backgroundColor: String?
    var textColor: String?
    var accentColor: String?
    
    // Typography
    var fontFamily: String?
    var fontWeight: FontWeight?
    var fontSize: FontSize?
    
    // Layout
    var cornerRadius: CornerRadius?
    var padding: Padding?
    var borderStyle: BorderStyle?
    
    // Effects
    var shadow: Shadow?
    var blurBackground: Bool?
    
    // Brand-specific
    var logoUrl: String?
    var iconName: String?  // SF Symbol name
    
    init(preset: UIStylePreset) {
        self.preset = preset
    }
    
    init(
        preset: UIStylePreset? = nil,
        primaryColor: String? = nil,
        secondaryColor: String? = nil,
        backgroundColor: String? = nil,
        textColor: String? = nil,
        accentColor: String? = nil,
        fontFamily: String? = nil,
        fontWeight: FontWeight? = nil,
        fontSize: FontSize? = nil,
        cornerRadius: CornerRadius? = nil,
        padding: Padding? = nil,
        borderStyle: BorderStyle? = nil,
        shadow: Shadow? = nil,
        blurBackground: Bool? = nil,
        logoUrl: String? = nil,
        iconName: String? = nil
    ) {
        self.preset = preset
        self.primaryColor = primaryColor
        self.secondaryColor = secondaryColor
        self.backgroundColor = backgroundColor
        self.textColor = textColor
        self.accentColor = accentColor
        self.fontFamily = fontFamily
        self.fontWeight = fontWeight
        self.fontSize = fontSize
        self.cornerRadius = cornerRadius
        self.padding = padding
        self.borderStyle = borderStyle
        self.shadow = shadow
        self.blurBackground = blurBackground
        self.logoUrl = logoUrl
        self.iconName = iconName
    }
    
    enum FontWeight: String, Codable {
        case light, regular, medium, semibold, bold
    }
    
    enum FontSize: String, Codable {
        case small, medium, large
    }
    
    enum CornerRadius: String, Codable {
        case none, small, medium, large, full
    }
    
    enum Padding: String, Codable {
        case compact, normal, spacious
    }
    
    enum BorderStyle: String, Codable {
        case none, subtle, prominent
    }
    
    enum Shadow: String, Codable {
        case none, subtle, medium, prominent
    }
}

/// UI component types
///
/// Categories:
/// - Input: Collect structured data from user
/// - Display: Show information (read-only)
/// - Action: Trigger actions (auth, execute, approve)
/// - Rich: Display rich content (emails, calendar, weather)
enum UIComponentType: String, Codable, CaseIterable {
    // === INPUT COMPONENTS ===
    case form = "form"                          // Multi-field form
    case picker = "picker"                      // Single selection picker
    case multiSelect = "multi_select"           // Multiple selection
    case datePicker = "date_picker"             // Date/time selection
    case contactPicker = "contact_picker"       // Contact selection
    case fileUpload = "file_upload"             // File/photo upload
    case locationPicker = "location_picker"     // Location selection
    
    // === CHOICE COMPONENTS (visual options) ===
    case optionButtons = "option_buttons"       // Horizontal/vertical button choices
    case optionCards = "option_cards"           // Card-based choices with descriptions
    case quickReplies = "quick_replies"         // Pill-shaped quick response buttons
    
    // === DISPLAY COMPONENTS ===
    case infoCard = "info_card"                 // Generic information display
    case weather = "weather"                    // Weather display
    case summary = "summary"                    // Task/progress summary
    case listView = "list_view"                 // List of items (read-only)
    case progress = "progress"                  // Progress indicator with details
    case styledList = "styled_list"             // Visual list with icons/cards
    case actionCards = "action_cards"           // Tappable suggestion cards
    case statusStrip = "status_strip"           // Single-line status display
    case infoChips = "info_chips"               // Missing info chips (tappable)
    
    // === ACTION COMPONENTS ===
    case confirmation = "confirmation"          // Yes/No confirmation gate
    case approval = "approval"                  // Approve action before execution
    case authGoogle = "auth_google"             // Google OAuth sign-in
    case authApple = "auth_apple"               // Sign in with Apple
    case authOAuth = "auth_oauth"               // Generic OAuth flow
    case execute = "execute"                    // Execute action button
    
    // === CREDENTIAL/AUTH COMPONENTS ===
    case apiKeyInput = "api_key_input"          // API key entry
    case credentialsInput = "credentials_input" // Username/password
    case authCallback = "auth_callback"         // OAuth callback handler
    case serviceConnect = "service_connect"     // Connect to a service
    
    // === RICH CONTENT ===
    case emailPreview = "email_preview"         // Email message preview
    case emailCompose = "email_compose"         // Email composition
    case calendarEvent = "calendar_event"       // Calendar event display/create
    case messagePreview = "message_preview"     // SMS/iMessage preview
    case documentPreview = "document_preview"   // Document/PDF preview
    case linkPreview = "link_preview"           // URL/link preview card
    
    /// Category of this component type
    var category: UIComponentCategory {
        switch self {
        case .form, .picker, .multiSelect, .datePicker, .contactPicker, .fileUpload, .locationPicker:
            return .input
        case .optionButtons, .optionCards, .quickReplies:
            return .input  // User makes a choice
        case .infoCard, .weather, .summary, .listView, .progress, .styledList, .statusStrip:
            return .display
        case .infoChips:
            return .input  // Tappable chips to provide missing info
        case .actionCards:
            return .action  // Tappable suggestions
        case .confirmation, .approval, .authGoogle, .authApple, .authOAuth, .execute,
             .apiKeyInput, .credentialsInput, .authCallback, .serviceConnect:
            return .action
        case .emailPreview, .emailCompose, .calendarEvent, .messagePreview, .documentPreview, .linkPreview:
            return .rich
        }
    }
    
    /// Whether this component requires user input/action
    var requiresUserInteraction: Bool {
        category != .display
    }
    
    /// Human-readable display name
    var displayName: String {
        switch self {
        case .form: return "Form"
        case .picker: return "Selection"
        case .multiSelect: return "Multi-Select"
        case .datePicker: return "Date Picker"
        case .contactPicker: return "Contact Picker"
        case .fileUpload: return "File Upload"
        case .locationPicker: return "Location"
        case .optionButtons: return "Choose"
        case .optionCards: return "Options"
        case .quickReplies: return "Reply"
        case .infoCard: return "Information"
        case .weather: return "Weather"
        case .summary: return "Summary"
        case .listView: return "List"
        case .styledList: return "List"
        case .actionCards: return "Suggestions"
        case .statusStrip: return "Status"
        case .infoChips: return "Missing"
        case .progress: return "Progress"
        case .confirmation: return "Confirm"
        case .approval: return "Approval Required"
        case .authGoogle: return "Sign in with Google"
        case .authApple: return "Sign in with Apple"
        case .authOAuth: return "Sign In"
        case .execute: return "Execute"
        case .apiKeyInput: return "Enter API Key"
        case .credentialsInput: return "Sign In"
        case .authCallback: return "Completing Sign In"
        case .serviceConnect: return "Connect Service"
        case .emailPreview: return "Email"
        case .emailCompose: return "Compose Email"
        case .calendarEvent: return "Calendar Event"
        case .messagePreview: return "Message"
        case .documentPreview: return "Document"
        case .linkPreview: return "Link"
        }
    }
}

/// Category of UI components
enum UIComponentCategory: String, Codable {
    case input      // Collect data
    case display    // Show info (read-only)
    case action     // Trigger actions
    case rich       // Rich content
}

/// Schema field definition
struct SchemaField: Codable, Hashable {
    let type: FieldType
    var label: String?
    var placeholder: String?
    var options: [String]?
    var validation: FieldValidation?
    var value: String?  // For hidden/prefilled fields
    var required: Bool?
    
    // Memberwise init for programmatic creation
    init(
        type: FieldType,
        label: String? = nil,
        placeholder: String? = nil,
        options: [String]? = nil,
        validation: FieldValidation? = nil,
        value: String? = nil,
        required: Bool? = nil
    ) {
        self.type = type
        self.label = label
        self.placeholder = placeholder
        self.options = options
        self.validation = validation
        self.value = value
        self.required = required
    }
    
    // Allow unknown keys to be ignored during decoding
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        // Try to decode type, default to .text if unknown
        if let typeString = try? container.decode(String.self, forKey: .type),
           let fieldType = FieldType(rawValue: typeString) {
            type = fieldType
        } else {
            type = .text
        }
        
        label = try? container.decodeIfPresent(String.self, forKey: .label)
        placeholder = try? container.decodeIfPresent(String.self, forKey: .placeholder)
        options = try? container.decodeIfPresent([String].self, forKey: .options)
        validation = try? container.decodeIfPresent(FieldValidation.self, forKey: .validation)
        value = try? container.decodeIfPresent(String.self, forKey: .value)
        required = try? container.decodeIfPresent(Bool.self, forKey: .required)
    }
    
    private enum CodingKeys: String, CodingKey {
        case type, label, placeholder, options, validation, value, required
    }
}

/// Field types for form schemas and rich content
enum FieldType: String, Codable, CaseIterable {
    // Basic input types
    case text
    case number
    case date
    case datetime
    case time
    case email
    case phone
    case url
    
    // Selection types
    case select
    case multiSelect = "multi_select"
    case boolean
    
    // File types
    case file
    case image
    case document
    
    // Rich content types
    case location
    case contact
    case currency
    
    // Display-only types (for info cards, previews)
    case richText = "rich_text"
    case html
    case markdown
    case json
    
    // Hidden/utility types
    case hidden
}

/// Field validation rules
struct FieldValidation: Codable, Hashable {
    var required: Bool?
    var minLength: Int?
    var maxLength: Int?
    var pattern: String?
}

// MARK: - Preview Helpers

extension UIRecipe {
    static var preview: UIRecipe {
        UIRecipe(
            componentType: .form,
            schema: [
                "amount": SchemaField(type: .number, label: "Amount", placeholder: "0.00"),
                "date": SchemaField(type: .date, label: "Receipt Date"),
                "category": SchemaField(type: .select, label: "Category", options: ["Food", "Transport", "Office"])
            ],
            requiredFields: ["amount", "date"],
            title: "Receipt Details",
            description: "Please provide the receipt information",
            isSubmitted: false
        )
    }
    
    static var submittedPreview: UIRecipe {
        UIRecipe(
            componentType: .form,
            schema: [
                "amount": SchemaField(type: .number, label: "Amount", placeholder: "0.00"),
                "date": SchemaField(type: .date, label: "Receipt Date"),
                "category": SchemaField(type: .select, label: "Category", options: ["Food", "Transport", "Office"])
            ],
            requiredFields: ["amount", "date"],
            title: "Receipt Details",
            description: "Please provide the receipt information",
            isSubmitted: true,
            submittedData: ["amount": "125.50", "date": "2024-01-15", "category": "Food"]
        )
    }
}

