"""
Chat endpoints for Bron interaction.
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from uuid import UUID, uuid4
from datetime import datetime
from typing import Optional, Any

router = APIRouter()


class MessageCreate(BaseModel):
    """Request model for sending a message."""
    bron_id: UUID
    content: str


class UIRecipe(BaseModel):
    """UI Recipe generated by Claude for structured input."""
    id: UUID
    component_type: str  # form, picker, confirmation, file_upload, etc.
    schema: dict[str, Any]
    required_fields: list[str]
    title: Optional[str] = None
    description: Optional[str] = None


class MessageResponse(BaseModel):
    """Response model for a chat message."""
    id: UUID
    bron_id: UUID
    role: str  # user, assistant
    content: str
    ui_recipe: Optional[UIRecipe] = None
    task_state_update: Optional[str] = None
    created_at: datetime


class ChatHistoryResponse(BaseModel):
    """Response model for chat history."""
    messages: list[MessageResponse]
    total: int


class UIRecipeSubmission(BaseModel):
    """Request model for submitting UI Recipe data."""
    recipe_id: UUID
    data: dict[str, Any]


@router.get("/{bron_id}/history", response_model=ChatHistoryResponse)
async def get_chat_history(bron_id: UUID, limit: int = 50, offset: int = 0):
    """Get chat history for a Bron."""
    # TODO: Implement with database
    return ChatHistoryResponse(messages=[], total=0)


@router.post("/message", response_model=MessageResponse)
async def send_message(request: MessageCreate):
    """Send a message to a Bron and get a response."""
    # TODO: Implement with Claude integration
    now = datetime.utcnow()
    return MessageResponse(
        id=uuid4(),
        bron_id=request.bron_id,
        role="assistant",
        content="I'm Bron, your AI assistant. How can I help you today?",
        ui_recipe=None,
        task_state_update=None,
        created_at=now,
    )


@router.post("/ui-recipe/submit", response_model=MessageResponse)
async def submit_ui_recipe(request: UIRecipeSubmission):
    """Submit data from a UI Recipe form."""
    # TODO: Implement with Claude integration
    raise HTTPException(status_code=404, detail="UI Recipe not found")

